package sshconfig

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/alexandr/nterm/internal/config"
)

// Render serializes NTerm server profiles into portable OpenSSH client
// configuration. Passwords, Keychain references and NTerm-only login commands
// are deliberately absent from this representation.
func Render(servers []config.SSHServer) ([]byte, error) {
	if len(servers) == 0 {
		return nil, errors.New("there are no SSH hosts to export")
	}
	var output bytes.Buffer
	output.WriteString("# Generated by NTerm. Credentials and post-login commands are not exported.\n\n")
	for index, server := range servers {
		normalized, err := config.NormalizeServer(server)
		if err != nil {
			return nil, fmt.Errorf("export server %q: %w", server.ID, err)
		}
		if index > 0 {
			output.WriteByte('\n')
		}
		comment := normalized.Name
		if normalized.Group != "" {
			comment += " — " + normalized.Group
		}
		fmt.Fprintf(&output, "# %s\n", comment)
		fmt.Fprintf(&output, "Host %s\n", normalized.ID)
		fmt.Fprintf(&output, "    HostName %s\n", normalized.Host)
		fmt.Fprintf(&output, "    Port %d\n", normalized.Port)
		fmt.Fprintf(&output, "    User %s\n", normalized.User)
		if normalized.KeyPath != "" {
			fmt.Fprintf(&output, "    IdentityFile %s\n", quoteToken(normalized.KeyPath))
		}
	}
	return output.Bytes(), nil
}

// WriteFile replaces only the path explicitly confirmed by the save dialog.
// A same-directory temporary file keeps the result atomic and mode 0600.
func WriteFile(path string, data []byte) error {
	path = filepath.Clean(strings.TrimSpace(path))
	if path == "" || path == "." {
		return errors.New("export path is empty")
	}
	directory := filepath.Dir(path)
	temporary, err := os.CreateTemp(directory, ".nterm-ssh-config-*")
	if err != nil {
		return fmt.Errorf("create SSH config export: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o600); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("secure SSH config export: %w", err)
	}
	if _, err := temporary.Write(data); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("write SSH config export: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("sync SSH config export: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close SSH config export: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("replace SSH config export: %w", err)
	}
	return nil
}

func quoteToken(value string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(value) + `"`
}
